import { NextRequest, NextResponse } from "next/server";

// This file has been intentionally removed to ensure OIDC callback query parameters are preserved.
// The OIDC provider should redirect directly to /oidc-callback?code=...&state=...
// ...file intentionally left blank...
